export default {
    header_title: "BIOMIID  Conditions de Service",
	last_update: "Dernière mise à jour : 28 mars 2024",
    section1_title: "Introduction",
	section1_content1: "Les conditions de service suivantes (« Conditions de service ») régissent votre utilisation du site Web Biomiid (le « Site ») et du service Biomiid accessible via le site (« Service »), tous deux exploités par Biomiid. (« Biomiid » ou « Nous »). En utilisant le Site et/ou le Service, vous acceptez irrévocablement que cette utilisation soit soumise aux présentes Conditions d'utilisation. Si vous n'acceptez pas ces conditions d'utilisation, vous ne pouvez pas utiliser le site ou le service. Si vous acceptez les présentes Conditions de service au nom d'une entité, vous déclarez que vous avez le pouvoir réel de lier cette entité aux présentes Conditions de service.",
	section1_content2: "Biomiid se réserve expressément le droit de modifier les Conditions de Service à tout moment, à sa seule discrétion, et sans préavis, en incluant une telle altération et/ou modification dans les présentes Conditions de Service, accompagnée d'un avis de la date d'entrée en vigueur de cette modification. Conditions d'utilisation modifiées.",
	section2_title: "Définitions",
    section2_subtitle1: "Utilisateurs autorisés",
	section2_content1: "signifie que les employés et sous-traitants du Client et de ses Sociétés Affiliées opèrent dans l'intérêt et au nom du Client.",
	section2_subtitle2: "Informations confidentielles",
	section2_content2: "désigne tout code, innovation, expertise, plans de produits et informations financières et techniques partagés dans le cadre du présent accord qui sont désignés comme privés au moment de leur divulgation ou qui, compte tenu des circonstances et de la nature des données divulguées, devraient être raisonnablement considérée comme confidentielle.",
	
	section2_subtitle3: "Informations client : ",
	section2_content3: "désigne toute information obtenue ou traitée par les Services au nom du Client, ainsi que toute information (y compris les détails du compte) fournie par le Client aux Services.",
	
	section2_subtitle4: "Documentation",
	section2_content4: "fait référence aux documents techniques de l'utilisateur final pour les Services fournis par Biomiid sur son site et peuvent être modifiés de temps à autre.",
	section2_subtitle5: "Utilisateurs finaux",
	section2_content5: "désigne les utilisateurs finaux du Client qui utilisent le Service pour interagir à des fins de vérification.",
	section2_subtitle6: "Droits intellectuels",
	section2_content6: "tous les droits de propriété intellectuelle, qu'ils soient enregistrés ou non, dans l'UE, aux États-Unis, au Royaume-Uni, en Californie et ailleurs, y compris, mais sans s'y limiter, les droits d'auteur, les marques déposées, les noms commerciaux et les droits de domaine de sites Web, ainsi que les droits correspondants ou connexes. Les demandes ou réclamations relatives à de tels droits ou licences, qu'elles soient explicitement accordées ou non, sont incluses dans les droits de propriété intellectuelle (Droits de PI), mais elles ne sont pas les seules.",
	section2_subtitle7: "Licence",
	section2_content7: "la licence fournie par Biomiid au licencié, qui comprend le droit non transférable et non exclusif d'utilisation et d'accès aux Services",
	section2_subtitle8: "Traitement des données privées",
	section2_content8: "toute action ou combinaison d'actions impliquant des informations privées, y compris, mais sans s'y limiter, la collecte, la commande, la conservation, la mise à jour, la modification, la récupération, la consultation, l'utilisation, la transmission, la distribution ou d'autres formes de fourniture de données, la combinaison, l'interconnexion, la protection, l’échange ou la suppression.",
	section2_subtitle9: "Portée d'utilisation",
	section2_content9: "fait référence aux restrictions d'utilisation des services qui sont détaillées dans les normes de procédures (SOP), y compris les restrictions numériques et les spécifications d'emballage de produits et de fonctionnalités.",
	section2_subtitle10: "Conditions",
	section2_content10: "désigne la période initiale des services concernés, ainsi que chaque période de renouvellement ultérieure (le cas échéant).",
	
	section3_title: "Processus de création de compte",
	section3_content1: "Pour passer des commandes, accéder ou utiliser un Service, les Clients et ses Personnes Autorisées peuvent avoir besoin de créer un compte Biomiid. La politique de confidentialité de Biomiid s'appliquera aux informations de compte. Afin que Biomiid puisse envoyer des alertes, des factures et d'autres données par courrier ou via le compte du Client, le Client doit conserver ces informations authentiques, valides et à jour. Les identifiants d'utilisateur, les informations d'identification ainsi que les autres informations d'identification d'accès au Service doivent tous être traités de manière totalement confidentielle par le client et ne doivent jamais être divulgués à quiconque. Le Client doit immédiatement suspendre l'accès de cet Utilisateur Autorisé à ses comptes et à tout Service si cet Utilisateur Autorisé quitte son emploi.",
	section3_content2: "Toutes les actions effectuées à l'aide des comptes, mots de passe ou identifiants d'accès du Client ou de ses Utilisateurs autorisés relèvent de la seule responsabilité du Client. En cas de faille de sécurité ou d'utilisation illégale du compte du client, Biomiid doit être informé sans délai. Les comptes ne peuvent être partagés que par les utilisateurs autorisés spécifiques auxquels ils ont été attribués.",
	
	section4_title: "Droits d'utilisation",
	section4_subtitle1: "Utilisation du service",
	section4_content1: "Biomiid accorde par la présente au client un droit mondial, non transférable, non exclusif et ne pouvant faire l'objet d'une sous-licence, d'accéder et d'utiliser les services identifiés sur le formulaire de commande du client pendant la durée applicable, uniquement pour des raisons commerciales du client et conformément aux les documents et le champ d'utilisation pertinent. Ce droit est soumis aux termes du présent Contrat. L'installation de Biomiid Code sur le site Internet du client ou dans ses applications peut être nécessaire pour les Services. Les droits accordés dans cette section permettent également l'installation et l'utilisation du code Biomiid pertinent sur les propriétés du client répertoriées sur le formulaire de commande du client dans certaines circonstances, sous réserve des exigences susmentionnées.",
	
	section4_subtitle2: "Utilisateurs autorisés",
	section4_content2: "Si leur utilisation est uniquement à l'avantage du Client et est conforme au présent Accord, le Client peut autoriser ses Utilisateurs autorisés à utiliser les Services. Tous les utilisateurs autorisés seront soumis au contrôle et à la responsabilité du client en ce qui concerne leur utilisation et leur respect du présent accord. L'utilisation combinée de tous les utilisateurs autorisés sera prise en compte dans toutes les limites de portée d'utilisation qui pourraient être en place.",
	
	section4_subtitle3: "Restrictions générales",
	section4_content3: "À l'exception des utilisateurs autorisés, il est interdit au client : (i) de louer, de louer, de copier, de transférer, de revendre, d'accorder une sous-licence, de partager du temps, de distribuer ou de donner de toute autre manière à des tiers l'accès à toute partie du service ; (ii) incorporer les Services (ou toute fraction de ceux-ci) avec, les utiliser avec ou fournir tout site, produit, application ou service autre que sur les Propriétés du Client ; et (iii) modifier ou créer une œuvre dérivée ; (iv) Le code source, les concepts sous-jacents, les techniques, les types de fichiers ou les API non publiques de chaque service (y compris le code Biomiid) ne peuvent pas faire l'objet d'une ingénierie inverse, désassemblés, décompilés, traduits. , ou tenté d'une autre manière, sauf autorisation explicite de la loi applicable et seulement après notification préalable à Biomiid ; (v) utiliser les Services pour développer un produit ou un service concurrent, ou copier ses caractéristiques ou son interface utilisateur ; (vi) enfreindre les précautions de sécurité, les limites de débit ou faire référence à une forme (telle que la surveillance d'événements) des Services ; ou (vii) personnaliser les Services (ou tout élément de ceux-ci) pour cesser d'envoyer des incidents ou des observations ou pour éviter de payer des frais.",
	
	section4_subtitle4: "Obligations du client",
	section4_content4: "Afin que le service puisse être utilisé sur les attributs du client et que les chercheurs du client collectent des données, les utilisent et les révèlent de la manière envisagée par le présent accord, le client s'engage à : (i) maintenir des conditions de service. le respect de la législation nationale sur ses Attributs Client ; (ii) toujours fournir des déclarations à ses utilisateurs finaux ; et (iii) utiliser les Services conformément à toutes les lois en vigueur.",
	
	section4_subtitle5: "Utilisation des données par les affiliés",
	section4_content5: "Sur une propriété du client qui appartient ou sous le contrôle d'un affilié, le client peut utiliser les services. Le Client sera responsable de la Propriété du Client et des Données Client associées de ses Affiliés, ainsi que de l'adhésion des Affiliés au présent Accord. Les conditions du présent Contrat peuvent également être incluses dans un Bon de commande distinct entre Biomiid et l'Affilié du Client. Les références au « Client » doivent désigner l'affilié client, ce qui formera un nouvel accord distinct entre l'associé client et Biomiid.",
	
	section5_title: "Droits du client",
	section5_subtitle1: "Droits sur les données du client",
	section5_content1: "Entre les parties, le Client détient tous les droits sur les informations du Client et les Propriétés du Client, y compris tous les droits de propriété intellectuelle. Afin de fournir le Service et les services associés, tels que le service client et l'assurance qualité, le Client accorde à Biomiid une autorisation non exclusive, internationale et libre de redevances pour collecter, utiliser, modifier et traiter uniquement les Données Client. Il crée des ensembles de données anonymisés distincts sur les achats et/ou les résultats des consommateurs qui ne reconnaissent pas le client ou les utilisateurs finaux et qui sont supprimés de tous les signifiants persistants (tels que le nom, l'adresse, l'e-mail et le numéro de téléphone.",
	section5_subtitle2: "Sécurité du client",
	section5_content2: "Afin de protéger les informations client dans le service contre toute utilisation non autorisée ou illégale, toute destruction involontaire ou illégale, tout égarement ou modification, ainsi que toute divulgation ou accès non autorisés, Biomiid mettra en place les mesures de sécurité techniques et organisationnelles nécessaires. En plus d'utiliser des pare-feu, des restrictions d'accès et d'autres technologies de sécurité pour protéger les données client contre toute divulgation et modification non autorisées, Biomiid stockera également les données client sur des serveurs qui sont des emplacements physiquement sûrs pour tous les utilisateurs.",
	
	section6_title: "Frais et paiement",
	section6_content1: "Le client consent à payer tous les frais selon le délai et la devise mentionnés dans le formulaire de commande concerné. Les frais facturés par Biomiid excluent tous les droits, et le client est responsable du paiement de tous les achats, utilisations, TVA, TPS, droits, retenues à la source et autres taxes et prélèvements pertinents, qu'ils soient locaux ou étrangers et non basés sur les bénéfices de Biomiid. Les obligations de paiement ne sont pas annulables et les paiements ne sont pas recouvrables, sauf indication claire dans le présent Accord. Sauf accord contraire écrit des parties, tous les frais non contestés sont payables en EUR.",
	section6_content2: "Si le client choisit de payer avec une carte de crédit, l'utilisateur est personnellement responsable soit (a) de la configuration de la recharge automatique sur son mode de paiement, soit (b) de s'assurer que son mode de paiement contient suffisamment d'argent pour couvrir tous les frais dus. . Biomiid se réserve le droit de restreindre l'accessibilité au Service si le(s) compte(s) du Client sont négatifs pour quelque raison que ce soit.",
	section6_content3: "Les factures seront envoyées par e-mail conformément à la Commande au Client s'il choisit de recevoir des factures et de payer en plusieurs fois comme convenu par Biomiid. Le client devra payer tous les frais non contestés dans les 30 jours suivant la date de facture, sauf indication contraire dans un bon de commande. Dans le cas où le client est en retard sur un paiement non contesté et n'effectue pas le paiement dans les 10 jours ouvrables suivant la réception d'un avis écrit, Biomiid peut imposer des frais de retard et le client accepte de les payer également.",
	
	section7_title: "Conditions et résiliation",
	
	section7_subtitle1: "Conditions",
	section7_content1: "À compter de la date d'émission et jusqu'à sa résiliation, le présent accord est en vigueur. Si toutes les conditions dudit ou de ces services sont caduques ou sont résiliées conformément aux dispositions de résiliation énoncées dans le présent accord, tout contrat peut être résilié en donnant à l'autre partie un préavis écrit de trente (30) jours.",
	section7_subtitle2: "Conditions de l'abonnement",
	section7_content2: "Le lancement d'une commande en ligne pour l'achat d'un service implique le consentement du client à payer tous les frais associés pendant toute la durée de l'abonnement. Sauf disposition expresse prévue dans le présent Contrat, le Client ne peut pas résilier ou annuler le présent Contrat. La Durée commence au moment où le Client prend en charge le Service pour la première fois, sauf si une date de début différente est indiquée sur le Bon de Commande concerné. Chaque souscription sera automatiquement prolongée pour des intervalles de douze mois ultérieurs.",
	section7_subtitle3: "Suspension du service",
	section7_content3: "Si le compte du client est en souffrance de paiement et que le client n'effectue pas de paiement dans les dix (10) jours suivant la réception d'un avis de Biomiid, Biomiid peut arrêter l'utilisation du ou des services par le client. De plus, si Biomiid décide qu'une suspension est nécessaire pour protéger la sécurité, la stabilité, la disponibilité ou l'intégrité du Service, Biomiid peut suspendre l'accès du Client au(x) Service(s).",
	
	section7_subtitle4: "Résiliation",
	section7_content4: "Le présent Contrat, ainsi que toute Commande connexe, peuvent être résiliés par l'une ou l'autre des parties si l'autre entité : (a) continue de ne pas remédier à toute violation grave du présent Contrat (y compris un refus de payer des frais incontestables) dans les trente (30) jours après la notification formelle décrivant la violation ; (b) ferme ses portes sans successeur ; ou (c) si la loi applicable le permet, recherche une garantie dans le cadre d'une insolvabilité, d'une mise sous séquestre, d'un acte de fiducie, d'un accord de créanciers, d'une structure ou d'une procédure comparable, ou si un successeur n'est pas nommé.",
	
	section8_title: "Informations confidentielles",
	
	section8_subtitle1: "Obligations de confidentialité",
	section8_content1: "Afin de remplir son obligation contractuelle et d'exercer ses privilèges en vertu du présent Accord, chaque entité (en tant que destinataire prévu) est tenue de : (a) détenir l'assurance et ne pas divulguer les données confidentielles de l'autre partie à des tiers, sauf si cela est expressément prévu. autorisé par le présent Contrat ; et (b) n'utiliser les informations confidentielles de l'autre partie qu'à ces fins. Chaque partie est autorisée à divulguer les informations confidentielles de l'autre partie à ses employés, agents ou sous-traitants et à ceux de ses sociétés affiliées qui ont besoin de les connaître ; cependant, chaque partie est toujours responsable de s'assurer que tout destinataire respecte les conditions de l'accord et que ces bénéficiaires sont soumis à des conditions imposées non moins protectrices que celles de la présente section.",
	
	section8_subtitle2: "Exclusion",
	section8_content2: "Ces obligations de non-divulgation ne concernent pas (et n'incluent pas) les détails qui : (a) sont et deviennent publiquement connus sans la faute de la partie destinataire ; (b) était déjà connu du destinataire prévu avant de recevoir les informations sensibles ; (c) est légitimement acquis par le destinataire auprès d'un tiers sans violer aucune obligation de confidentialité ; ou (d) appartient uniquement au destinataire prévu sans utiliser les informations confidentielles. Si la loi le permet, une partie peut également révéler les informations secrètes de l'autre partie dans la mesure où cela est nécessaire en vertu de la loi ou d'un mandat délivré, à condition qu'elle coopère avec les efforts de l'autre partie pour maintenir la confidentialité des informations.",
	
	
	section9_title: "Indemnisation",
	section9_content: "Lorsque des réclamations de tiers sont déposées contre Biomiid en raison des propriétés du client, le client s'engage à protéger Biomiid contre de telles réclamations (y compris les produits ou services proposés dans le cadre des propriétés du client). Dans le cas où Biomiid serait tenu responsable de tout dommage ou coût (y compris les frais juridiques raisonnables) liés à des réclamations de tiers, le Client défendra Biomiid et le dégagera de toute responsabilité. Si la résolution oblige Biomiid à admettre sa responsabilité, à payer les sommes que le Client est tenu de payer en vertu du présent Contrat, ou à entreprendre ou à s'abstenir de prendre toute mesure, le Client ne pourra régler aucun litige sans l'accord écrit explicite de Biomiid. Le client et Biomiid coopéreront de manière raisonnable dans la défense de toute réclamation à laquelle Biomiid participe par l'intermédiaire d'avocats de son choix et à ses propres frais.",
	
	section10_title: "Avertissements",
	section10_content: "CHAQUE PRODUIT DE LA TECHNOLOGIE BIOMIID ET SERVICE ASSOCIÉ EST FOURNI « TEL QUEL » ET « SELON LA DISPONIBILITÉ ». AUCUN DE BIOMIID OU DE SES FOURNISSEURS NE FAIT AUCUNE AUTRE RÉCLAMATION, IMPLICITE OU EXPRESSE, LÉGALE OU AUTRES, QUI NE SONT PAS SANS AUCUNE GARANTIE, TITRE, ADÉQUATION À UN USAGE SPÉCIFIQUE, NON-VIOLATION OU EXEMPT D'ERREURS OU UTILISATION SÉCURISÉE DU SERVICE, POUR DANS TOUTE LA MESURE, BIOMIID N'OFFRE AUCUNE GARANTIE CONCERNANT LES INFORMATIONS OU LE CONTENU DISPONIBLES PAR LE SERVICE. LES OBLIGATIONS DE SÉCURITÉ EXPRESSES PRISES PAR BIOMIID DANS LE CADRE DU PRÉSENT CONTRAT NE SONT PAS UNE GARANTIE QUE CES INITIATIVES ÉVITERONT UNE VIOLATION DE LA SÉCURITÉ DES DONNÉES. BIOMIID N'EST PAS RESPONSABLE DE : (A) TOUTE PROPRIÉTÉ DU CLIENT, INFORMATION DU CLIENT OU PRODUITS ET SERVICES NON-BIOMIID (Y COMPRIS TOUT RETARDS SIGNALÉS, TOUTE PERTURBATION OPÉRATIONNELLE, ERREURS DE TRANSMISSION, DÉFAILLANCES DE SÉCURITÉ OU AUTRES PROBLÈMES CAUSÉS PAR CES ÉLÉMENTS) ; (B) UTILISATION DE LA TECHNOLOGIE BIOMIID (C) TOUTE ACTION OU DÉCISION PRISE PAR LE CLIENT POUR LES SERVICES BIOMIID. LES CLIENTS DÉTIENNENT DES DROITS ADÉQUATS. NÉFAIS, CES DROITS STATUTAIRES EXIGENT DES GARANTIES EN VERTU DE LA LÉGISLATION APPROPRIÉE, LE CAS ÉCHÉANT, ET SERONT LIMITÉS PENDANT UNE CERTAINE PÉRIODE.",
	

  }